Произошла ошибка, почини её:
SyntaxError: The requested module '/node_modules/use-sync-external-store/with-selector.js?v=ce34cff8' does not provide an export named 'useSyncExternalStoreWithSelector'